### ISSUE TITLE
zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by rotexpro** [bwalsh0/Stereo-Camera-Path-Planning#2]
```
[CameraMatrix_L = 
[[2756.143    0.     521.702]
 [   0.    2812.585  327.337]
 [   0.       0.       1.   ]]

CameraMatrix_R = 
[[1670.954    0.    1205.327]
 [   0.    2524.826  254.341]
 [   0.       0.       1.   ]]

RotationStereo = 
[[ 0.975  0.044 -0.217]
 [-0.031  0.998  0.062]
 [ 0.219 -0.054  0.974]]

TranslationStereo = 
[[-11.733]
 [ -2.918]
 [ 12.289]]

DistCoeffStereo_L = 
[[  -1.132 -135.598   -0.015   -0.123 6468.129]]

DistCoeffStereo_R = 
[[-3.015  2.26  -0.001 -0.877 -7.401]]

Q = 
[[    1.        0.        0.    -7785.808]
 [    0.        1.        0.      842.122]
 [    0.        0.        0.    16191.828]
 [    0.        0.        0.058    -0.   ]]

Left MSE: 0.185031
Right MSE: 0.185031
Overall MSE: 0.242667 (8 image pairs)

Traceback (most recent call last):

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\rotim\desktop\stereo path planning\stereo-camera-path-planning\calibration.py", line 124, in <module>
    plt.subplot(223); plt.imshow(img11); plt.title('ROI_L: ' + str(img11.shape))

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\_api\deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\pyplot.py", line 2647, in imshow
    **kwargs)

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\_api\deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\axes\_axes.py", line 5488, in imshow
    im.set_data(X)

  File "C:\Users\rotim\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\image.py", line 724, in set_data
    if self._A.min() < 0 or high < self._A.max():

  File "C:\Users\rotim\AppData\Roaming\Python\Python37\site-packages\numpy\ma\core.py", line 5701, in min
    axis=axis, out=out, **kwargs).view(type(self))

  File "C:\Users\rotim\AppData\Roaming\Python\Python37\site-packages\numpy\core\_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)

ValueError: zero-size array to reduction operation minimum which has no identity
```
**Calibration file**

Currently that is the error i'm getting. i narrowed it down to the remap function which plots black pixels for img1 and img2.

Please will need help moving forward, thank you

**Comment by iLUVE69** [comment]
try changing the image search window from (5,5) to (3,3)
